release: added some basic logging

diff --git a/release b/release
--- a/release
+++ b/release
@@ -18,8 +18,13 @@ changelogurl="https://github.com/$ghuser/$progname/blob/master/$changelog"
 editorcmd="vim +8"
 netrccmd="gpg --quiet --decrypt $HOME/.netrc.gpg" # for curl --netrc-file /dev/stdin
 
+log() {
+        printf "%s: " "$(date +'%H:%M:%S')" >&2
+        echo "$@" >&2
+}
+
 die() {
-        echo "error:" "$@" >&2
+        log "error:" "$@"
         exit 1
 }
 
@@ -44,6 +49,7 @@ relversion="$(echo "$currversion" \
     rel == "minor" { print $1, $2+1, 0 }
     rel == "patch" { print $1, $2, $3+1 }
 ')"
+log "new release version is $relversion"
 
 sed "4i ## $relversion\n\n$reldate\n\n- WRITE CHANGELOG HERE (delete version to abort)\n" "$changelog" > "$changelog.tmp"
 $editorcmd "$changelog.tmp"
@@ -52,12 +58,16 @@ if ! grep -q "^## $relversion$" "$changelog.tmp"; then
 fi
 mv "$changelog.tmp" "$changelog"
 
+log "committing $changelog and creating new tag $relversion"
 git add "$changelog"
 git commit --message="$changelog: $relversion"
 git tag "$relversion"
 
+log "building binaries"
 make clean
 make cross-build
+
+log "creating archives"
 mkdir "archive.tmp"
 cp "$license" "$readme" "$changelog" "archive.tmp"
 for binname in "$progname-$relversion-"*; do
@@ -67,12 +77,13 @@ for binname in "$progname-$relversion-"*; do
         tar -czf "$binname.tar.gz" "$binname"
         sha256sum "$binname.tar.gz" >> "$progname-$relversion-sha256-checksums.txt"
         mv "$binname" "archive.tmp"
+        log "created $binname.tar.gz"
 done
 rm -rf "archive.tmp"
 
-printf "\nplease make sure that everything is all right, --amend now if you have to.\n"
+echo "please make sure that everything is all right, --amend now if you have to."
 while true; do
-        printf "%s" "push to remote? [YES/NO] "
+        printf "push to remote and create new release? [YES/NO] "
         read -r ans
         case "$ans" in
         "YES")
@@ -84,6 +95,7 @@ while true; do
         esac
 done
 
+log "pushing to remote"
 git push
 git push --tags
 
@@ -96,6 +108,7 @@ ghpost() {
          "$3"
 }
 
+log "creating new release with name $relversion"
 reldata="$(jq -n -c --arg relversion "$relversion" --arg changelogurl "$changelogurl" \
 '{
     "tag_name": $relversion,
@@ -103,8 +116,13 @@ reldata="$(jq -n -c --arg relversion "$relversion" --arg changelogurl "$changelo
     "body": "[changelog](\($changelogurl)#\($relversion | gsub("\\."; "")))"
 }')"
 relinfo="$(ghpost "application/json" "$reldata" "$relapiurl")"
+log "created new release $(echo "$relinfo" | jq -r '.html_url')"
 
 reluploadurl="$(echo "$relinfo" | jq -r '.upload_url' | sed 's/{.*$//')"
 for asset in "$progname-$relversion-"*".tar.gz" "$progname-$relversion-"*"-checksums.txt"; do
+        log "uploading $asset"
         assetinfo="$(ghpost "$(file --brief --mime-type "$asset")" "@$asset" "$reluploadurl?name=$asset")"
+        log "uploaded $(echo "$assetinfo" | jq -r '.browser_download_url')"
 done
+
+log "done!"
